### ISSUE TITLE
emulator wont remember last rom played

### ISSUE THREAD

**Issue by supersonicjc** [dborth/vbagx#404]
**Describe the bug**
open the emulator for the first time either through the homebrew browser or the channel loader and when you get to your game list you should be able to just start up on the last game that was played
**To Reproduce**
open the emulator up and instead of it remembering the last game that was played before you shut it down the emulator jumps anywhere from 10 to 40 games up the game list

**Expected behavior**
version 2.4.0 the emulator would remember the last game that was played before you close it down, with the new update it jumps up the game list when you first load the emulator up

I did report this on the nes and will be making bug requests on that and the snes but it should remember the last game that was played before you turn the emulator off and its no longer doing that

**Comment by dborth** [comment]
This is likely a timing issue because of a delay between when your device is mounted and ready and when the file browser starts up and tries to list/display the contents. I have absolutely no intention of looking at this. If someone else fixes it and makes a PR, this will be fixed. Otherwise it won't.

Please stop harassing me.
