### ISSUE TITLE
All GBA games lag

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dborth/vbagx#92]
```
What steps will reproduce the problem?
1.  Load GBA game
2.  Attempt to play    


What is the expected output? What do you see instead?

From reading older and current issues it seems as if most users are able 
to play GBA games without lag, ie, normally.  Every game I try lags.  
Sprites move so slow that the game is unplayable.  Also, the music at 
times plays correctly, but mostly there is a "crackling" noise underneath 
the audio.  GB and GBC games run perfectly.        


Does this issue occur on VBA-M r781 (http://vba-
m.ngemu.com/vbam/vbacompiles/msvc2008/VisualBoyAdvance781.7z)? If so, 
please report the issue to the VBA-M forum.

No.


What version of the product are you using? On GameCube or Wii?

Gamecube


Please provide any additional information below.

I'm using the Datel SD Media Card.  I have it in the second memory card 
slot.  I'm running roms off of an SD Ultra II 2GB card (15MB/s).  I have 
tried to change the filter settings, but this doesn't help.    


```

Original issue reported on code.google.com by `BrianJos...@gmail.com` on 26 Apr 2009 at 7:26

**Comment by moomeow96** [comment]
I don't know if you used a hacked Wii cause I didn't really read it (I'm lazy lol), but I have been experiencing the same thing on this console, although it's more like a frequent stutter, if anything. In other words, it'll skip a few frames every now and again, deeming strategy games and RPGs like Superstar Saga way harder (and I still wonder how I made it to Jokes End lmao). I think there's an option in the latest version called "GBA Frameskip", probably on to keep the game running smoothly. I haven't tried turning it off yet, though, so if you do it before me, I wish you luck! Anyways, I think disabling Vsync helps too, but I could be very wrong. Also, the staff seems to be more active nowadays, so you could probably try posting about this again if the problem persists. Also, if you need me, ping me with the @ symbol, and then my username (no space in between), followed by the message you want to send me. If you don't ping me, it's very likely that I won't respond because I don't get notifications for anything but a ping (Android app bug lol). I hope you get your problem fixed soon or already have it fixed!
